package Entity;
// Generated Jun 29, 2017 7:35:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cancha generated by hbm2java
 */
public class Cancha  implements java.io.Serializable {


     private int canchaId;
     private Tamanocancha tamanocancha;
     private String nombre;
     private Set reservas = new HashSet(0);

    public Cancha() {
    }

	
    public Cancha(int canchaId) {
        this.canchaId = canchaId;
    }
    public Cancha(int canchaId, Tamanocancha tamanocancha, String nombre, Set reservas) {
       this.canchaId = canchaId;
       this.tamanocancha = tamanocancha;
       this.nombre = nombre;
       this.reservas = reservas;
    }
   
    public int getCanchaId() {
        return this.canchaId;
    }
    
    public void setCanchaId(int canchaId) {
        this.canchaId = canchaId;
    }
    public Tamanocancha getTamanocancha() {
        return this.tamanocancha;
    }
    
    public void setTamanocancha(Tamanocancha tamanocancha) {
        this.tamanocancha = tamanocancha;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


