package Entity;
// Generated Jun 29, 2017 7:35:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hora generated by hbm2java
 */
public class Hora  implements java.io.Serializable {


     private int horaId;
     private int hora;
     private Set reservas = new HashSet(0);

    public Hora() {
    }

	
    public Hora(int horaId) {
        this.horaId = horaId;
    }
    public Hora(int horaId, int hora, Set reservas) {
       this.horaId = horaId;
       this.hora = hora;
       this.reservas = reservas;
    }
   
    public int getHoraId() {
        return this.horaId;
    }
    
    public void setHoraId(int horaId) {
        this.horaId = horaId;
    }
    public int getHora() {
        return this.hora;
    }
    
    public void setHora(int hora) {
        this.hora = hora;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }

}


