package Entity;
// Generated Jun 29, 2017 7:35:39 PM by Hibernate Tools 4.3.1



/**
 * Invitacion generated by hbm2java
 */
public class Invitacion  implements java.io.Serializable {


     private int invitacionId;
     private Reserva reserva;
     private Usuario usuario;

    public Invitacion() {
    }

	
    public Invitacion(int invitacionId) {
        this.invitacionId = invitacionId;
    }
    public Invitacion(int invitacionId, Reserva reserva, Usuario usuario) {
       this.invitacionId = invitacionId;
       this.reserva = reserva;
       this.usuario = usuario;
    }
   
    public int getInvitacionId() {
        return this.invitacionId;
    }
    
    public void setInvitacionId(int invitacionId) {
        this.invitacionId = invitacionId;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


