package Entity;
// Generated Jun 29, 2017 7:35:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int reservaId;
     private Cancha cancha;
     private Usuario usuario;
     private Date fecha;
     private Hora hora;
     private Boolean pagada;
     private String tokeninvitacion;
     private Set invitacions = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(int reservaId) {
        this.reservaId = reservaId;
    }
    public Reserva(int reservaId, Cancha cancha, Usuario usuario, Date fechainicio, Hora hora, Boolean pagada, String tokeninvitacion, Set invitacions) {
       this.reservaId = reservaId;
       this.cancha = cancha;
       this.usuario = usuario;
       this.fecha = fechainicio;
       this.hora = hora;
       this.pagada = pagada;
       this.tokeninvitacion = tokeninvitacion;
       this.invitacions = invitacions;
    }
   
    public int getReservaId() {
        return this.reservaId;
    }
    
    public void setReservaId(int reservaId) {
        this.reservaId = reservaId;
    }
    public Cancha getCancha() {
        return this.cancha;
    }
    
    public void setCancha(Cancha cancha) {
        this.cancha = cancha;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fechainicio) {
        this.fecha = fechainicio;
    }
    public Hora getHora() {
        return this.hora;
    }
    
    public void setHora(Hora hora) {
        this.hora = hora;
    }
    public Boolean getPagada() {
        return this.pagada;
    }
    
    public void setPagada(Boolean pagada) {
        this.pagada = pagada;
    }
    public String getTokeninvitacion() {
        return this.tokeninvitacion;
    }
    
    public void setTokeninvitacion(String tokeninvitacion) {
        this.tokeninvitacion = tokeninvitacion;
    }
    public Set getInvitacions() {
        return this.invitacions;
    }
    
    public void setInvitacions(Set invitacions) {
        this.invitacions = invitacions;
    }




}


