package Entity;
// Generated Jun 29, 2017 7:35:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tamanocancha generated by hbm2java
 */
public class Tamanocancha  implements java.io.Serializable {


     private int tamanocanchaId;
     private String tamanocancha;
     private Integer precio;
     private Set canchas = new HashSet(0);

    public Tamanocancha() {
    }

	
    public Tamanocancha(int tamanocanchaId) {
        this.tamanocanchaId = tamanocanchaId;
    }
    public Tamanocancha(int tamanocanchaId, String tamanocancha, Integer precio, Set canchas) {
       this.tamanocanchaId = tamanocanchaId;
       this.tamanocancha = tamanocancha;
       this.precio = precio;
       this.canchas = canchas;
    }
   
    public int getTamanocanchaId() {
        return this.tamanocanchaId;
    }
    
    public void setTamanocanchaId(int tamanocanchaId) {
        this.tamanocanchaId = tamanocanchaId;
    }
    public String getTamanocancha() {
        return this.tamanocancha;
    }
    
    public void setTamanocancha(String tamanocancha) {
        this.tamanocancha = tamanocancha;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Set getCanchas() {
        return this.canchas;
    }
    
    public void setCanchas(Set canchas) {
        this.canchas = canchas;
    }




}


